spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

jwt:
  secret: ======================ANTONIO=Spring===========================

logging:
  level:
    org:
      springframework:
        security: DEBUG